# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de82c3a72e399c6da8fe6341b06cdf01be3b6eefa24f8eb22da7ac956451e3797d88427c8f21ffc663368e11c3865f71e46a6e8d1b3b6ca51726f42ccc24e0d7

test:
  secret_key_base: 1a940ca87decad4f236a513d53d7a8cdd450476cd6d54ee791148c480e195fb7a938a48828116dd9bba63f4525e071ef6d5aa9a3fa9d5b73d11f91abdbde4647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
